### ISSUE TITLE
Incorrect link to Python style guide

### ISSUE THREAD

**Issue by aholmes** [AI-READI/software-development-best-practices#5] opened 2023-02-04 01:13 UTC
[Code development](https://github.com/AI-READI/software-development-best-practices/blob/main/main/software-development-best-practices-for-ai-readi/code-development.md#2-code-development) item 2.1.1 links to Python's contribution guide:

> This guide is a comprehensive resource for [contributing](https://devguide.python.org/#contributing) to [Python](https://www.python.org/)

Is it intended to link to one of the Python style guides, e.g., [PEP 8](https://peps.python.org/pep-0008/)? Google also has a [Python style guide](https://google.github.io/styleguide/pyguide.html).

**Comment by bvhpatel** [comment] 2023-05-09 00:35
Yes this was intended to refer to PEP8. This has been addressed in here: https://github.com/AI-READI/software-development-best-practices/blob/tools-core-comments/main/software-development-best-practices-for-ai-readi/code-development.md. This will be pushed to the main branch when we have addressed all the comments from the Tools Core.

**Closed as completed** 2023-05-11 17:55 UTC
